#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

if [ "$#" -eq 0 ]; then
    scp $1 $2@$3:~/$4
fi

echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"