#!/usr/bin/env bash
# Install nginx

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart