#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure redirection
sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me' << EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default symlink to avoid conflicts
sudo rm -f /etc/nginx/sites-enabled/default

# Check Nginx configuration syntax
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx