#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  oussama_frontend
        bind *:80
        mode http
        default_backend oussama_backend
backend oussama_backend
        balance roundrobin
        server 430003-web-01 100.25.102.204:80 check
        server 430003-web-02 54.236.41.224:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart