#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
#!/usr/bin/env bash
if service nginx status | grep -q "not running"; then
    sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
    sudo service nginx restart
fi