#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

num=1
while [ $num -le 10 ]
do
	if [ $num = 4 ]; then
		echo "bad luck"
	elif [ $num = 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	num=$(( num+1 ))
done
